### ISSUE TITLE
Slight error in the computation of the l2_lrp backward function

### ISSUE THREAD

**Issue by romain-xu-darme** [SrishtiGautam/PRP#1]
Hello Srishti! 
I've recently looked back at the code for PRP, and I may have notice a small error in your formula for computing the backward pass across the layer computing the L2 similarity. 
https://github.com/SrishtiGautam/PRP/blob/3a8548396a2827432f9d6f87b96e46aaca58c6df/lrp_general6.py#L2127C1-L2128C34
I may be mistaken but it seems that you are computing the square of the L2 distance twice (once in the variable l2, the second time when computing d). I'm not exactly sure whether this will significantly change any result obtained using PRP (since relevance is propagated proportionally  to the sum of all relevance scores) but I thought you should know.
Best regards
Romain

**Comment by SrishtiGautam** [comment]
Hi Romain,
Thank you so much for pointing this out. However, I am sure there would be insignificant changes in the result, like you mentioned that the relevances are propagated proportionally across all layers and neurons. 

I did a small experiment to confirm this, the PRP maps using the new code (without square in line 2127) vs the old code, and the heatmaps look identical, while the difference lies sometimes in fifth floating point digit (therefore, insignificant):

![new_Overlay_prp_20_1435_stop_1331867282 avi_image2](https://github.com/SrishtiGautam/PRP/assets/25633736/096fddd8-aced-42c5-a811-51573b153ae3)
![old_Overlay_prp_20_1435_stop_1331867282 avi_image2](https://github.com/SrishtiGautam/PRP/assets/25633736/2b2e1732-165f-42f5-a003-55f35498aa34)


I will update the code for future use. 

Thanks a lot! This was good to know.

Best,
Srishti

**Comment by romain-xu-darme** [comment]
That's what I thought :) Have a nice day
